services:
  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: saltedlolly-cloudflare-ddns_ui_1
      APP_PORT: 3000

  ui:
    image: ghcr.io/saltedlolly/cloudflare-ddns-ui@sha256:ee9065c12898476d285e186aa5fa03f87b37e416b258047108149825bcc0af08
    container_name: saltedlolly-cloudflare-ddns_ui_1
    hostname: saltedlolly-cloudflare-ddns_ui_1
    init: true
    restart: unless-stopped
    environment:
      - APP_DATA_DIR=/data
      - NODE_ENV=production
    volumes:
      - cloudflare-ddns-data:/data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  cloudflare-ddns:
    image: ghcr.io/saltedlolly/cloudflare-ddns@sha256:a3df0e8b5db673a7ac015806b133522a6e8e22a9c6bd3463a49015beb7f246ba
    container_name: saltedlolly-cloudflare-ddns_cloudflare-ddns_1
    hostname: saltedlolly-cloudflare-ddns_cloudflare-ddns_1
    network_mode: host
    init: true
    restart: unless-stopped
    environment:
      - APP_DATA_DIR=/data
    volumes:
      - cloudflare-ddns-data:/data
    healthcheck:
      test: ["CMD", "sh", "-c", "test -f /data/status.json && grep -q '\"status\": \"running\"' /data/status.json || exit 1"]
      interval: 1m
      timeout: 20s
      retries: 6
    depends_on:
      - ui

volumes:
  cloudflare-ddns-data:
